### ISSUE TITLE
iOS version or Publish on Git

### ISSUE THREAD

**Issue by NaiRobley** [mclintprojects/ideabag2#1]
Hello, mine is just a request.

A friend recommended the app but there is no iOS version. So I was wondering if the ideas can be published elsewhere say on Github or if an iOS app is in the pipeline since I would like to learn through the ideas of projects in your app.

Thank you in advance.

**Comment by mclintprojects** [comment]
I think I might make a web based version of the app, very soon. It won't have all the features of the native version (initially) but at least all the ideas will be available to browse through. If you want to help let me know here. I'll update this issue when I am ready to begin.

**Comment by NaiRobley** [comment]
@mclintprojects Thank you for getting back to me. I am willing and ready to collaborate and help you on the web-based version of the app.

**Comment by mclintprojects** [comment]
@NaiRobley i have actually finished the first draft of the web app. i made it with Vue.js and for now it only supports browsing through the ideas. no bookmarking, progress status or notes yet. the UI isn't even too pretty. if you switch to the 'web-version' branch of this repository you should be able to see the work I've already done. i'm currently trying to host it on firebase. if all goes well, I'll send a link and you take a look and contribute or suggest changes.

**Comment by mclintprojects** [comment]
@NaiRobley you can access the early web version here https://ideabag2.firebaseapp.com/

**Comment by NaiRobley** [comment]
@mclintprojects Thank you for the link. Checking it out
